name: Generate Embeddings
on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * 0'

jobs:
    generate-embeddings:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Fetch Data
              run: make fetch-data

            - name: Download current DB
              run: make fetch-db

            - name: Install Ollama
              run: curl -fsSL https://ollama.com/install.sh | sh

            - name: Pull Model
              run: ollama pull mxbai-embed-large

            - name: Generate Embeddings
              run: go run . index
              env:
                CLIENT_ID: asd
                CLIENT_SECRET: asd
                FQDN: http://localhost

            - name: Create DB.zip
              run: zip -r db.zip db

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: db.zip
                asset_name: db.zip
                tag: '0.0.1'
                overwrite: true
    
    build-image:
      runs-on: ubuntu-24.04-arm
      needs: generate-embeddings
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Log in to registry
          uses: docker/login-action@v3
          with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Fetch DB
          run: make fetch-db

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: |
                ghcr.io/shopwarelabs/copilot-extension
            cache-from: type=gha,scope=copilot
            cache-to: type=gha,scope=copilot,mode=max
            provenance: false

    build-ollama:
      runs-on: ubuntu-24.04-arm
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Log in to registry
          uses: docker/login-action@v3
          with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: Dockerfile.ollama
            push: true
            tags: |
                ghcr.io/shopwarelabs/copilot-extension/ollama
            cache-from: type=gha,scope=ollama
            cache-to: type=gha,scope=ollama,mode=max
            provenance: false
